name: build and test

on: [push, pull_request]

jobs:

  job:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v2.2.0
      with:
        node-version: '12.x'

    - run: npm install

    - run: npm run lint

    - run: npm run build-production --if-present

    - run: npm test
      env:
        CI: true
